### ISSUE TITLE
How to use in concert with mini_repo?

### ISSUE THREAD

**Issue by isaacsanders** [hexpm/hexdocs#12]

**Comment by wojtekmach** [comment]
I think this might be pretty challenging given hexdocs is pretty specific to hexpm. Hexdocs processes docs by picking up a SQS job that was triggered by S3 tarball push, it then processes the tarball and pushes individual docs files (htmls, csses etc) to storage and fastly. If you want to end up with similar setup I think you could use hexdocs in your organisation, but I'd probably start with simple docs hosting on mini_repo, I think that would be a useful feature. If you'd like to work on that a PR to mini_repo would be appreciated. Note, there's very basic support for docs on mini_repo already, if you publish a docs tarball, it's accessible:

    curl --head http://localhost:4000/repos/test_repo/docs/foo-0.1.0.tar.gz

but yeah, I think a way to access the actual docs would be great.

I don't think this issue is actionable in this repo, again, I think hexdocs is pretty specific to hexpm, so I'm gonna go ahead and close it but feel free to continue discussing it here!

**Comment by wojtekmach** [comment]
I thought about this a bit more and getting even the most basic docs hosting in mini_repo is probably a lot of work (and if it's too simplistic it would be pretty jarring for people accustomed to our docs story) so I think for now it's better to keep it out of scope of mini_repo after all.

**Comment by isaacsanders** [comment]
I was thinking that generating docs and putting them into an object store like cephs should allow you to host a static site with the docs. It wouldn't be exactly easily navigable, but 🤷‍♂
