### ISSUE TITLE
API Reference missing from CSV 3.0.1

### ISSUE THREAD

**Issue by beatrichartz** [hexpm/hexdocs#28]
I've tried reverting and publishing this again, but the [API reference seems to be missing from version 3.0.1](https://hexdocs.pm/csv/3.0.1/api-reference.html), see https://github.com/beatrichartz/csv/issues/114 - anything I need to fix on my end?

**Comment by ericmj** [comment]
The files you uploaded are missing the contents of the `api-reference.html` file (see https://repo.hex.pm/docs/csv-3.0.1.tar.gz) so something went wrong when running the `mix docs` task from `ex_doc`.

I cannot reproduce the issue when running `mix docs` in your repo. I would suggest running `mix docs` yourself and see what happens.

I will close this issue since it's not caused by hexdocs, but feel free to keep adding to it.
