### ISSUE TITLE
Canonical links of elixir library

### ISSUE THREAD

**Issue by nulian** [hexpm/hexdocs#41]
I saw an issue before about canonical links and that it was fixed for phoenix.

But so often I have the same issue while searching for elixir docs for a specific function it points me to old versions.

Like if you search for `elixir file ls` the first link you get is to elixir 1.13.4 of hexdocs.

Would be nice if the elixir library gets like pointed to the latest version.

**Comment by ericmj** [comment]
We generate the correct canonical link for newer docs as can be seen if you check under the `<head>` tag on https://hexdocs.pm/elixir/1.16.3/Kernel.html. Unfortunately for older docs we generated a canonical link that points to the latest version for that minor version `1.15` instead of the very latest version.

To fix this we have to rewrite the files of all the older versions.
